name: "CI: Build, Test and Publish"

on:
  push:
    branches: [main, IN-654-Elastic-search-from-azure]
    paths:
      - "**.cs"
      - "**.tsx"
      - "**.js"
      - "**.csproj"
      - "**.props"
      - "**.targets"
      - "**.slnx"
      - "**.json"
      - ".github/workflows/main.yml"
  pull_request:
    branches: [main]
    paths:
      - "**.cs"
      - "**.tsx"
      - "**.js"
      - "**.csproj"
      - "**.props"
      - "**.targets"
      - "**.sln"
      - "**/Client/**/*.json"
      - ".github/workflows/main.yml"

jobs:
  dotnet-format:
    name: dotnet-format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Run dotnet format
        run: dotnet format --exclude ./examples/** --verify-no-changes

  build:
    name: build
    runs-on: ubuntu-latest
    needs: dotnet-format
    defaults:
      run:
        shell: pwsh

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: 1
      SIGN_FILE: false
      PROJECT_NAME: XperienceCommunity.ElasticSearch

    steps:
      - uses: actions/checkout@v4

      - name: "Install Node.js from package.json version"
        uses: actions/setup-node@v4
        with:
          node-version-file: ./src/${{ env.PROJECT_NAME }}/Admin/Client/package.json

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
          dotnet-version: "8.0.x"

      - name: Install dependencies
        run: dotnet restore --locked-mode

      - name: Build Solution
        run: dotnet build --configuration Release --no-restore

      - name: Test Solution
        run: dotnet test --configuration Release --no-build --no-restore

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            ./src/${{ env.PROJECT_NAME }}/bin/Release/
            ./src/${{ env.PROJECT_NAME }}/obj/Release/

  pack-nugget:
    name: Pack NuGet Package
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: 1
      SIGN_FILE: false
      PROJECT_NAME: XperienceCommunity.ElasticSearch

    steps:
      - uses: actions/checkout@v4

      - name: "Install Node.js from package.json version"
        uses: actions/setup-node@v4
        with:
          node-version-file: ./src/${{ env.PROJECT_NAME }}/Admin/Client/package.json

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Pack NuGet package
        run: dotnet pack ./src/${{ env.PROJECT_NAME }} --configuration Release -o ./nupkg

      - name: Upload NuGet Package
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: ./nupkg/*.nupkg

  publish-nugget:
    name: Publish NuGet Package to GitHub Packages
    runs-on: ubuntu-latest
    needs: pack-nugget
    permissions:
      contents: read
      packages: write

    steps:
      - name: Download NuGet Package
        uses: actions/download-artifact@v4
        with:
          name: nuget-package
          path: ./nupkg

      - name: Publish to GitHub Packages
        run: dotnet nuget push ./nupkg/*.nupkg --source https://nuget.pkg.github.com/BiQ-Bluesoft/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
