name: "CI: Build and Test"

on:
  push:
    branches: [main, IN-654-Elastic-search-from-azure]
    paths:
      - "**.cs"
      - "**.tsx"
      - "**.js"
      - "**.csproj"
      - "**.props"
      - "**.targets"
      - "**.sln"
      - "**/Client/**/*.json"
      - ".github/workflows/main.yml"
  pull_request:
    branches: [main]
    paths:
      - "**.cs"
      - "**.tsx"
      - "**.js"
      - "**.csproj"
      - "**.props"
      - "**.targets"
      - "**.sln"
      - "**/Client/**/*.json"
      - ".github/workflows/main.yml"

jobs:
  dotnet-format:
    name: dotnet-format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Run dotnet format
        run: dotnet format --exclude ./examples/** --verify-no-changes

  build:
    name: build
    runs-on: ubuntu-latest
    needs: dotnet-format
    defaults:
      run:
        shell: pwsh

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: 1
      SIGN_FILE: false
      PROJECT_NAME: XperienceCommunity.ElasticSearch

    steps:
      - uses: actions/checkout@v4

      - name: "Install Node.js from package.json version"
        uses: actions/setup-node@v4
        with:
          node-version-file: ./src/${{ env.PROJECT_NAME }}/Admin/Client/package.json

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Install dependencies
        run: dotnet restore --locked-mode

      - name: Build Solution
        run: dotnet build --configuration Release --no-restore

      - name: Test Solution
        run: dotnet test --configuration Release --no-build --no-restore

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            ./src/${{ env.PROJECT_NAME }}/bin/Release/
            ./src/${{ env.PROJECT_NAME }}/obj/Release/

  publish-nugget:
    name: Publish NuGet Package to Feedz.io
    runs-on: ubuntu-latest
    needs: build

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: 1
      SIGN_FILE: false
      PROJECT_NAME: XperienceCommunity.ElasticSearch

    steps:
      - uses: actions/checkout@v4

      - name: "Install Node.js from package.json version"
        uses: actions/setup-node@v4
        with:
          node-version-file: ./src/${{ env.PROJECT_NAME }}/Admin/Client/package.json

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Pack NuGet package
        run: dotnet pack ./src/${{ env.PROJECT_NAME }} --configuration Release -o ./nupkg

      - name: Publish to Feedz.io
        run: dotnet nuget push ./nupkg/*.nupkg --source https://f.feedz.io/bluesoft/elastic/nuget/index.json --api-key ${{ secrets.FEEDZ_API_KEY }}
